### ISSUE TITLE
Error while installing dependency

### ISSUE THREAD

**Issue by thim0o** [Igglybuff/linky#1]
When i'm installing the dependencies 'myjdapi' i giving me the following error:

```
Failed building wheel for pycrypto
Running setup.py clean for pycrypto
Failed to build pycrypto
```
Is there a way I can use linky without jdownloader support?

**Comment by Igglybuff** [comment]
You can probably get away with commenting out this line:

https://github.com/Igglybuff/linky/blob/master/requirements.txt#L1

before running `pip3 install .` if you're not planning on using JDownloader :)
